### ISSUE TITLE
[BP-2167] Fix some incorrect icons/logo's in our media repository on GitHub

### ISSUE THREAD

**Issue by remcotolsma** [buckaroo-it/Media#3]
In https://github.com/buckaroo-it/Media/commit/4a542156aba926548f24aee822b6b2f774792bb5 you have added the AfterPay Riverty logo, I don't think this is the official AfterPay Riverty logo 🤔.

![](https://cdn.riverty.design/logo/riverty-checkout-logo.svg)

https://cdn.riverty.design/logo/riverty-checkout-logo.svg

You can also check the Pronamic Pay logos library: 
https://github.com/pronamic/wp-pay-logos/tree/1.11.0/dist/methods/afterpay-riverty

---

Out of curiosity, how many of your customers are actively using AfterPay/Riverty? We rarely come across this payment method in the wild. Is it worth investing in this payment method? In other words, does it make sense to update the Buckaroo integration within Pronamic Pay with the new AfterPay/Riverty naming/branding?

**Comment by Buckaroo-Rene** [comment]
Sorry for the late reply and thank you for sharing this with us. We will change the AfterPay .SVG logo together with some other logo's which needs to be improved. We have created a ticket for it internally (BP-2167).

**Comment by Buckaroo-Rens** [comment]
Fixed in latest PR. 

@remcotolsma regarding your question about Riverty. It's a very popular payment method in the Benelux. But more for regular ecommerce. I know you guys are working a lot for 'Stichtingen' so it won't be so interesting for them.
