### ISSUE TITLE
BP-3127 Trim iDEAL issuer NN logo size

### ISSUE THREAD

**Issue by sven4all** [buckaroo-it/Media#31]
The SVG of the Nationale Nederlanden icon is 100kb, A smaller simplified version would be preferable https://github.com/buckaroo-it/Media/blob/main/iDEAL%20bank%20issuers/SVG/NN.svg.

**Comment by Buckaroo-Rene** [comment]
@sven4all ,
Thanks for pointing out this difference.
For now we where able to trime the image a bit as a quick solution.
